### ISSUE TITLE
HMR Websocket connection fails

### ISSUE THREAD

**Issue by grischaerbe** [Gitpod-Samples/template-sveltekit#3]
### Bug description

Opening this repo in a fresh Gitpod Workspace and having a look at the dev tools of the preview reveals that the Websocket connection fails and the browser is reloading the page continuously.

### Steps to reproduce

- Open this repo in a fresh gitpod.io workspace with the provided button in the README
- Open the preview that opens up in the "Simple Browser" tab in a regular Chrome tab
- Open the dev tools
- See the console for Websocket connection errors

### Expected behavior

HMR should work, the Websocket connection should not fail.

### Example repository

https://github.com/gitpod-io/template-sveltekit

**Comment by bklein-tfg** [comment]
I see this was converted to a question, is there a fix for it available?

**Comment by mikenikles** [comment]
Please check the diff in #4 at https://github.com/gitpod-io/template-sveltekit/pull/4/files for how to fix this.

In short, HMR now runs on port 3000.
